Adds images to homepage via the asset-server
canonical-web-and-design/certification.ubuntu.com pull request #5
Opened 2019-07-12 13:29 UTC by b-m-f

# Done 
creates the homepage

Fixes https://github.com/canonical-web-and-design/base-squad/issues/621

# QA
`./run` and make sure that the homepage matches https://certification.ubuntu.com/

2019-07-12 14:40 UTC, webteam-app commented
Starting demo at: https://certification-ubuntu-com-canonical-web-and-design-pr-5.run.demo.haus/

2019-07-12 14:45 UTC, anthonydillon requested changes
Looking good. Few things in QA:
 - [x] The hero section has some local images which are missing and should be replaced with asset-server:
![Screenshot_2019-07-12 Certified hardware Ubuntu](https://user-images.githubusercontent.com/1413534/61136740-079c4700-a4bc-11e9-8af5-0586cc04bcd4.png)
 - [x] The page title and favicon is missing

2019-07-15 08:06 UTC, b-m-f commented
@anthonydillon No idea whats wrong with the demo services. The pictures are loaded from the asset server on the latest commit :)

Favicon and title are added!

2019-07-16 09:45 UTC, anthonydillon approved these changes
Awesome :+1:

2019-07-16 10:41 UTC, merged